name: block chain school 1st task

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Compile
        run: npx hardhat compile

      - name: Lint Solidity
        run: npx solhint 'contracts/**/*.sol'

      - name: Lint TypeScript
        run: npx eslint .

      - name: Run Tests
        run: npx hardhat test

      - name: Slither Analysis
        run: |
          npm install -g slither-analyzer
          slither . || true
